version: "3.8"

services:
  docling-api:
    build: .
    ports:
      - "8991:8991"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=${EMBEDDING_SERVICE_URL}
      - EMBEDDING_SERVICE_API_KEY=${EMBEDDING_SERVICE_API_KEY}
      - UPLOAD_DIR=/app/uploads
      - PROCESSED_DIR=/app/processed
    volumes:
      - uploads_data:/app/uploads
      - processed_data:/app/processed
    depends_on:
      - redis
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8991 --workers 2

  celery-worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=${EMBEDDING_SERVICE_URL}
      - EMBEDDING_SERVICE_API_KEY=${EMBEDDING_SERVICE_API_KEY}
      - UPLOAD_DIR=/app/uploads
      - PROCESSED_DIR=/app/processed
      - C_FORCE_ROOT=true
    volumes:
      - uploads_data:/app/uploads
      - processed_data:/app/processed
    depends_on:
      - redis
    restart: unless-stopped
    command: celery -A app.celery worker --loglevel=info

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: Add a Celery monitoring dashboard
  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker
    command: celery -A app.celery flower --port=5555

volumes:
  uploads_data:
  processed_data:
  redis_data:
