apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: UVZhUk9xdm5hNFNjU0w=
---
apiVersion: v1
kind: Secret
metadata:
  name: deepdoc-secret
type: Opaque
data:
  EMBEDDING_SERVICE_API_KEY: UVZhUk9xdm5hNFNjU0w=
