name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        run: echo "${{ secrets.V75_REGISTRY_PASSWORD }}" | docker login registry.v75inc.dev -u "${{ secrets.V75_REGISTRY_USER }}" --password-stdin

      - name: Build and push API image
        run: |
          docker build -t ${{ vars.V75_REGISTRY_IMAGE_API }}:${{ github.ref_name }} -t ${{ vars.V75_REGISTRY_IMAGE_API }}:latest ./
          docker push ${{ vars.V75_REGISTRY_IMAGE_API }}:${{ github.ref_name }}
          docker push ${{ vars.V75_REGISTRY_IMAGE_API }}:latest

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
          draft: false
          prerelease: false
